from django.contrib import admin
from .models import *
# from .. import models as md

# admin.site.register(md.Address)
# admin.site.register(md.Categories)
# admin.site.register(md.Customers)
# admin.site.register(md.Feedbacks)
# admin.site.register(md.Invoices)
# admin.site.register(md.Orders)
# admin.site.register(md.OrderDetail)
# admin.site.register(md.PaymentMethod)
# admin.site.register(md.Payments)
# admin.site.register(md.Products)
# admin.site.register(md.Status)
admin.site.register(Address)
admin.site.register(Categories)
admin.site.register(Customers)
admin.site.register(Feedbacks)
admin.site.register(Invoices)
admin.site.register(Orders)
admin.site.register(OrderDetail)
admin.site.register(PaymentMethod)
admin.site.register(Payments)
admin.site.register(Products)
admin.site.register(Status)
