# Generated by Django 5.2 on 2026-06-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
