# Generated by Django 5.2 on 2026-06-23 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("ct_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("pym_id", models.AutoField(primary_key=True, serialize=False)),
                ("method", models.CharField()),
            ],
            options={
                "db_table": "payment_method",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("st_id", models.AutoField(primary_key=True, serialize=False)),
                ("state", models.CharField()),
                ("just_for_test", models.BooleanField(blank=True, null=True)),
                ("test", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "status",
            },
        ),
        migrations.CreateModel(
            name="Feedbacks",
            fields=[
                ("fb_id", models.AutoField(primary_key=True, serialize=False)),
                ("fb_date", models.DateField(auto_now_add=True)),
                ("feedback", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "feedbacks",
            },
        ),
        migrations.CreateModel(
            name="Invoices",
            fields=[
                ("inv_id", models.AutoField(primary_key=True, serialize=False)),
                ("invoic_total", models.IntegerField()),
                ("payment_total", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("or_id", models.AutoField(primary_key=True, serialize=False)),
                ("or_data", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="customer",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        db_column="status",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shop.status",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("py_id", models.AutoField(primary_key=True, serialize=False)),
                ("py_date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField()),
                (
                    "invoices_inv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shop.invoices",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        db_column="method",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shop.paymentmethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("pr_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.CharField(null=True)),
                ("amount_in_stock", models.IntegerField(blank=True, null=True)),
                ("hot", models.BooleanField(blank=True, null=True)),
                ("saved_time", models.TimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shop.categories",
                    ),
                ),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                ("od_id", models.AutoField(primary_key=True, serialize=False)),
                ("unit_price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                (
                    "or_field",
                    models.ForeignKey(
                        db_column="or_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shop.orders",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shop.products",
                    ),
                ),
            ],
            options={
                "db_table": "order_detail",
            },
        ),
    ]
