# Generated by Django 6.0.4 on 2026-05-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("adr_id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.TextField()),
                ("state", models.TextField()),
            ],
            options={
                "db_table": "address",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("ct_id", models.AutoField(primary_key=True, serialize=False)),
                ("slug", models.TextField()),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("cs_id", models.AutoField(primary_key=True, serialize=False)),
                ("cs_name", models.TextField()),
                ("cs_lastname", models.TextField()),
                ("birth_date", models.TextField(blank=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("create_time", models.TextField()),
                ("points", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "customers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Feedbacks",
            fields=[
                ("fb_id", models.AutoField(primary_key=True, serialize=False)),
                ("fb_date", models.TextField()),
                ("feedback", models.TextField()),
            ],
            options={
                "db_table": "feedbacks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Invoices",
            fields=[
                ("inv_id", models.AutoField(primary_key=True, serialize=False)),
                ("invoic_total", models.IntegerField()),
                ("payment_total", models.IntegerField()),
            ],
            options={
                "db_table": "invoices",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                ("od_id", models.AutoField(primary_key=True, serialize=False)),
                ("unit_price", models.IntegerField()),
                ("quantity", models.IntegerField()),
            ],
            options={
                "db_table": "order_detail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("or_id", models.AutoField(primary_key=True, serialize=False)),
                ("or_data", models.TextField()),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("pym_id", models.AutoField(primary_key=True, serialize=False)),
                ("method", models.TextField()),
            ],
            options={
                "db_table": "payment_method",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("py_id", models.AutoField(primary_key=True, serialize=False)),
                ("py_date", models.TextField()),
                ("amount", models.IntegerField()),
            ],
            options={
                "db_table": "payments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("pr_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("price", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="static/shop/images/products")),
                ("amount_in_stock", models.IntegerField(blank=True, null=True)),
                ("hot", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("st_id", models.AutoField(primary_key=True, serialize=False)),
                ("state", models.TextField()),
            ],
            options={
                "db_table": "status",
                "managed": False,
            },
        ),
    ]
