# Generated by Django 5.2 on 2026-06-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="saved_time",
        ),
    ]
